### ISSUE TITLE
Q: Why fibers?

### ISSUE THREAD

**Issue by jrochkind** [splattael/minitest-around#24]
Not an issue, just wondering if you could share just a few words on why the current version of minitest-around uses Fibers, what motivated that choice?  

I am greatly missing `around` from Minitest/spec, and am considering this gem, but want to understand what it's doing and why first to make sure I understand what I'm getting into. It's not obvious to me the benefit of using Fibers there instead of a simpler implementation (like in older versions of this gem?). 

Thanks for any information!

**Comment by splattael** [comment]
@jrochkind I don't know if you are still fighting `Fiber`s.

One option is to simply use `def around` in your spec avoid the `Fiber` implementation.

For more complete and nicer minitest hooks you might have a look at @jeremyevans' [minitest-hooks](https://github.com/jeremyevans/minitest-hooks)!

**Comment by splattael** [comment]
As `minitest-hooks` supports [block-based arounds](https://github.com/jeremyevans/minitest-hooks/commit/fb1ca0ca787b435608f0e17ea17c7729fd5cfd64) **without** the usage of Fibers, I will abandon `minitest-around` soonish.

Please note that `minitest-hooks` have more minitest-like [behavior](https://github.com/jeremyevans/minitest-hooks#behavior).

Closing.
