### ISSUE TITLE
Tests sometimes failing

### ISSUE THREAD

**Issue by balasankarc** [splattael/minitest-around#29]
Hi,
I packaged (as part of Diaspora packaging chain) and am maintaining minitest-around for Debian. One of the tests sometimes fail during the build. I don't quite know how to reproduce that, so this is just a blind shot. The following is the fail log

  1) Failure:
Outer::Inner#test_0001_testing [/«PKGBUILDDIR»/test/nested_spec.rb:12]:
--- expected
+++ actual
@@ -1 +1 @@
-[:before, :begin, :ibefore, :ibegin, :during, :iend, :iafter, :end, :after]
+[:ibegin, :ibefore, :during, :iafter, :iend, :before, :begin, :ibefore, :ibegin, :during, :iend, :iafter, :end, :after]

It seems [:ibegin, :ibefore, :during, :iafter, :iend] is getting appended before the expected result. Since I am not much experienced in Ruby, I don't know what causes this. 

Is it something related to the "test:isolated" portion in Rakefile? Coz, the file used in Debian to run tests is as follows
`require 'rake/testtask'`
`Gem2Deb::Rake::TestTask.new do |test|`
`  test.test_files = TEST_FILES`
`  test.libs << 'test'`
`  test.verbose = true`
`end`

This is because, Debian must use packaged ruby gems to run the tests and not Bundler.

Any chance you can help me? Thanks. :)

**Comment by splattael** [comment]
Hi,

thanks for reporting!

In order to reproduce this random test failure I need more information :)

Could you please provide:
* The full output of test run (including `--seed`)
* Ruby version
* Output of `gem list`

Kind regards,
  Peter

**Comment by balasankarc** [comment]
@splattael This contains the entire log. It uses Ruby 2.1 - https://reproducible.debian.net/rb-pkg/unstable/amd64/ruby-minitest-around.html

I'll post the `gem list` output next time I reproduce this issue in my local system.

**Comment by balasankarc** [comment]
@splattael Thanks for the quick response. :) Another release any time soon??

**Comment by balasankarc** [comment]
Oh, you released. I missed that. Thanks  very much.

**Comment by splattael** [comment]
@balasankarc You're too fast for me ;)

Ok, I've managed to reproduce the problem using the `seed` provided in the log. Thank you! :+1: 

I've just released `v0.3.2`.

As a longstanding Debian user (since Hamm) I'm very excited to see this gem being packaged! :green_heart:
