### ISSUE TITLE
Compatibility with `Mutex` and `Monitor`

### ISSUE THREAD

**Issue by dorianmariefr** [splattael/minitest-around#36]
Hi,

I'm not sure if I'm doing something wrong, or is this a ruby bug or is this a minitest-around bug, just letting you know of this issue

https://github.com/thoughtbot/climate_control/issues/46#issuecomment-1179128261

```ruby
require "climate_control"
require "minitest/around"
require "minitest/autorun"

class Foo
  def self.country_code
    ENV.fetch("SMS_DEFAULT_COUNTRY_CODE", "++41")
  end
end

describe Foo do
  around do |test|
    ClimateControl.modify(SMS_DEFAULT_COUNTRY_CODE: nil) do
      test.call
    end
  end

  def test_nested
    ClimateControl.modify(SMS_DEFAULT_COUNTRY_CODE: "++56") do
      assert_equal Foo.country_code, "++56"
    end

    assert_equal Foo.country_code, "++41"
  end
end
```

**Comment by grosser** [comment]
this can't possibly work:
```
MUTEX = Mutex.new
MUTEX.synchronize do
  MUTEX.synchronize do
   puts 1
  end
end
```

**Comment by dorianmariefr** [comment]
I replaced with `Monitor` (that's what we use)

```
MONITOR = Monitor.new
MONITOR.synchronize do
  MONITOR.synchronize do
    puts 1
  end
end
```

**Comment by grosser** [comment]
ahh 🤦 should have copied ...
the reason it does not work then is that `around` uses `Fiber`
the `around` runs in a different fiber than the `it`

```ruby
MONITOR = Monitor.new
fib = Fiber.new { MONITOR.synchronize { Fiber.yield } }
fib.resume # run fiber until the yield
MONITOR.synchronize { puts 1 }
fib.resume # finish fiber -> boom
```

**Comment by grosser** [comment]
don't think there is any good fix for this ... 
use before/after
or use the old way of doing around: https://github.com/splattael/minitest-around/commit/4ee5ea7282a5a60cf405c549cfc8b5a766396417
which gets the ordering of multiple before calls wrong, so might work, but also might lead to new bugs
